- alias: Sunset
  trigger:
    platform: sun
    event: sunset
  action: 
    service: script.scene_and_notify
    data:
      scene: "Relax"
      message: ":city_sunset: Turning the lights down a notch..."