- name: concentrate
  entities:
    group.all_lights:
      state: on
      brightness: 254
      xy_color: [0.3691, 0.3719]

- name: energize
  entities:
    group.all_lights:
      state: on
      brightness: 254
      xy_color: [0.3314, 0.3301]

- name: relax
  entities:
    group.all_lights:
      state: on
      brightness: 144
      xy_color: [0.519, 0.4152]

- name: "on"
  entities:
    group.all_lights:
      state: on

- name: "off"
  entities:
    group.all_lights:
      state: off
